### ISSUE TITLE
FK_ConnectNet return error -2

### ISSUE THREAD

**Issue by EhsanFaghih** [mkranga/FKAttend#2]
Hi
Why FK_ConnectNet return error -2?
Thanks

**Comment by mkranga** [comment]
-2= RUNERR_NO_OPEN_COMM = Error that the device has been not connected .

https://kupdf.net/download/72836238-fkattend-manuala_5a7010ebe2b6f5e65acf9939_pdf

**Comment by EhsanFaghih** [comment]
Hi,
The device is connected but FK_ConnectNet return error -2 !!!
Could the parameters be wrong?
I am using fkattend.dll version 2.8.10.604.
For connect to device i used this code in C#:

[DllImport("FKAttend.dll", CharSet = CharSet.Ansi)]
...
FK_ConnectNet(1, "192.168.1.100", 5005, 5000, 0, 0);
